export const weekDays = [
    {
        direction: "Молодёж.",
        time: "06:30",
        color: "#006DFF",
        hours: 6,
        minutes: 30,
    },
    {
        direction: "Одинцово",
        time: "06:45",
        color: "#202020",
        hours: 6,
        minutes: 44,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Молодёж.",
        time: "07:00",
        color: "#006DFF",
        hours: 7,
        minutes: 0,
    },
    {
        direction: "Одинцово",
        time: "07:20",
        color: "#202020",
        hours: 7,
        minutes: 20,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Молодёж",
        time: "07:30",
        color: "#006DFF",
        hours: 7,
        minutes: 30,
    },
    {
        direction: "Молодёж",
        time: "08:05",
        color: "#006DFF",
        hours: 8,
        minutes: 5,
    },
    {
        direction: "Одинцово",
        time: "07:35",
        color: "#202020",
        hours: 7,
        minutes: 35,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Одинцово",
        time: "07:45",
        color: "#202020",
        hours: 7,
        minutes: 45,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Молодёж.",
        time: "07:55",
        color: "#006DFF",
        hours: 7,
        minutes: 55,
    },
    {
        direction: "Молодёж.",
        time: "07:55",
        color: "#006DFF",
        hours: 7,
        minutes: 55,
    },
    {
        direction: "Молодёж.",
        time: "08:05",
        color: "#006DFF",
        hours: 8,
        minutes: 5,
    },
    {
        direction: "Одинцово",
        time: "08:15",
        color: "#202020",
        hours: 8,
        minutes: 15,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Молодёж.",
        time: "08:20",
        color: "#006DFF",
        hours: 8,
        minutes: 20,
    },
    {
        direction: "Молодёж.",
        time: "08:35",
        color: "#006DFF",
        hours: 8,
        minutes: 35,
    },
    {
        direction: "Одинцово",
        time: "08:45",
        color: "#202020",
        hours: 8,
        minutes: 45,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Молодёж.",
        time: "08:55",
        color: "#006DFF",
        hours: 8,
        minutes: 55,
    },
    {
        direction: "Молодёж.",
        time: "09:00",
        color: "#006DFF",
        hours: 9,
        minutes: 0,
    },
    {
        direction: "Молодёж.",
        time: "09:20",
        color: "#006DFF",
        hours: 9,
        minutes: 20,
    },
    {
        direction: "Одинцово",
        time: "09:25",
        color: "#202020",
        hours: 9,
        minutes: 25,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Молодёж.",
        time: "09:30",
        color: "#006DFF",
        hours: 9,
        minutes: 30,
    },
    {
        direction: "Молодёж.",
        time: "09:45",
        color: "#006DFF",
        hours: 9,
        minutes: 45,
    },
    {
        direction: "Молодёж.",
        time: "09:50",
        color: "#006DFF",
        hours: 9,
        minutes: 50,
    },
    {
        direction: "Одинцово",
        time: "10:25",
        color: "#202020",
        hours: 10,
        minutes: 25,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Молодёж.",
        time: "10:35",
        color: "#006DFF",
        hours: 10,
        minutes: 35,
    },
    {
        direction: "Одинцово",
        time: "10:55",
        color: "#202020",
        hours: 10,
        minutes: 55,
    },
    {
        direction: "Одинцово",
        time: "По приб.",
        color: "#202020",
        hours: "",
        minutes: "",
    },
    {
        direction: "Одинцово",
        time: "11:15",
        color: "#202020",
        hours: 11,
        minutes: 15,
    },
    {
        direction: "Одинцово",
        time: "11:35",
        color: "#202020",
        hours: 11,
        minutes: 35,
    },
    {
        direction: "Молодёж.",
        time: "11:15",
        color: "#006DFF",
        hours: 11,
        minutes: 15,
    },
    {
        direction: "Молодёж.",
        time: "11:25",
        color: "#006DFF",
        hours: 11,
        minutes: 25,
    },
    {
        direction: "Молодёж.",
        time: "11:35",
        color: "#006DFF",
        hours: 11,
        minutes: 35,
    },
    {
        direction: "Молодёж.",
        time: "12:05",
        color: "#006DFF",
        hours: 12,
        minutes: 5,
    },
    {
        direction: "Одинцово",
        time: "11:45",
        color: "#202020",
        hours: 11,
        minutes: 45,
    },
    {
        direction: "Одинцово",
        time: "12:15",
        color: "#202020",
        hours: 12,
        minutes: 15,
    },
    {
        direction: "Слав.Б.",
        time: "12:40",
        color: "#8DB929",
        hours: 12,
        minutes: 40,
    },
    {
        direction: "Слав.Б.",
        time: "13:40",
        color: "#8DB929",
        hours: 13,
        minutes: 40,
    },
    {
        direction: "Одинцово",
        time: "12:45",
        color: "#202020",
        hours: 12,
        minutes: 45,
    },
    {
        direction: "Одинцово",
        time: "13:05",
        color: "#202020",
        hours: 13,
        minutes: 5,
    },
    {
        direction: "Молодёж.",
        time: "13:15",
        color: "#006DFF",
        hours: 13,
        minutes: 15,
    },
    {
        direction: "Молодёж.",
        time: "14:30",
        color: "#006DFF",
        hours: 14,
        minutes: 30,
    },
];

export const saturday = [];
export const sunday = [];

// 14:30
