/*
export const weekDaysT = [
    {
        direction: "Молодёж.",
        time: "06:30",
        color: "#006DFF",
        hours: 6,
        minutes: 30,
    },
];
*/

export const timeTable = {
    weekDays: [
        {
            direction: "Одинцово",
            time: "01:20",
            color: "#202020",
            hours: 1,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "06:30",
            color: "#006DFF",
            hours: 6,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "06:45",
            color: "#202020",
            hours: 6,
            minutes: 45,
            whereTo: "toMoscow",
        },

        {
            direction: "Молодёжная",
            time: "07:00",
            color: "#006DFF",
            hours: 7,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "07:20",
            color: "#202020",
            hours: 7,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "07:30",
            color: "#006DFF",
            hours: 7,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "07:35",
            color: "#202020",
            hours: 7,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "07:45",
            color: "#202020",
            hours: 7,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "07:55",
            color: "#006DFF",
            hours: 7,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "07:55",
            color: "#006DFF",
            hours: 7,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "08:05",
            color: "#006DFF",
            hours: 8,
            minutes: 5,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "08:15",
            color: "#202020",
            hours: 8,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "08:20",
            color: "#006DFF",
            hours: 8,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "08:35",
            color: "#006DFF",
            hours: 8,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "08:45",
            color: "#202020",
            hours: 8,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "08:55",
            color: "#006DFF",
            hours: 8,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:00",
            color: "#006DFF",
            hours: 9,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:20",
            color: "#006DFF",
            hours: 9,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "09:25",
            color: "#202020",
            hours: 9,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:30",
            color: "#006DFF",
            hours: 9,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:45",
            color: "#006DFF",
            hours: 9,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:50",
            color: "#006DFF",
            hours: 9,
            minutes: 50,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "10:25",
            color: "#202020",
            hours: 10,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "10:35",
            color: "#006DFF",
            hours: 10,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "10:55",
            color: "#202020",
            hours: 10,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "11:15",
            color: "#202020",
            hours: 11,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "11:15",
            color: "#006DFF",
            hours: 11,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "11:25",
            color: "#006DFF",
            hours: 11,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "11:35",
            color: "#006DFF",
            hours: 11,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "11:45",
            color: "#202020",
            hours: 11,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Слав.бульвар",
            time: "12:40",
            color: "#8DB929",
            hours: 12,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "12:45",
            color: "#202020",
            hours: 12,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "13:15",
            color: "#006DFF",
            hours: 13,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "13:25",
            color: "#202020",
            hours: 13,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "14:00",
            color: "#202020",
            hours: 14,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "14:40",
            color: "#202020",
            hours: 14,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "14:55",
            color: "#006DFF",
            hours: 14,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "15:23",
            color: "#202020",
            hours: 15,
            minutes: 23,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "16:00",
            color: "#202020",
            hours: 16,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "16:40",
            color: "#202020",
            hours: 16,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "16:35",
            color: "#006DFF",
            hours: 16,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "17:00",
            color: "#202020",
            hours: 17,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "17:20",
            color: "#202020",
            hours: 17,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "18:00",
            color: "#006DFF",
            hours: 18,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "17:55",
            color: "#202020",
            hours: 17,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "18:10",
            color: "#202020",
            hours: 18,
            minutes: 10,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "18:35",
            color: "#006DFF",
            hours: 18,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "18:40",
            color: "#202020",
            hours: 18,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "18:55",
            color: "#006DFF",
            hours: 18,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "19:20",
            color: "#202020",
            hours: 19,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "19:45",
            color: "#202020",
            hours: 19,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "19:55",
            color: "#202020",
            hours: 19,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "20:05",
            color: "#006DFF",
            hours: 20,
            minutes: 5,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "20:10",
            color: "#202020",
            hours: 20,
            minutes: 10,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "20:25",
            color: "#202020",
            hours: 20,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "20:35",
            color: "#006DFF",
            hours: 20,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "20:40",
            color: "#202020",
            hours: 20,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "21:00",
            color: "#202020",
            hours: 21,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "21:20",
            color: "#202020",
            hours: 21,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "21:30",
            color: "#006DFF",
            hours: 21,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Слав.бульвар",
            time: "21:40",
            color: "#8DB929",
            hours: 21,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "21:50",
            color: "#202020",
            hours: 21,
            minutes: 50,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "22:05",
            color: "#202020",
            hours: 22,
            minutes: 5,
            whereTo: "toMoscow",
        },
        {
            direction: "Слав.бульвар",
            time: "22:25",
            color: "#8DB929",
            hours: 22,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "22:40",
            color: "#202020",
            hours: 22,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "22:55",
            color: "#202020",
            hours: 22,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "23:15",
            color: "#202020",
            hours: 23,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Слав.бульвар",
            time: "23:20",
            color: "#8DB929",
            hours: 23,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "23:40",
            color: "#202020",
            hours: 23,
            minutes: 40,
            whereTo: "toMoscow",
        },
        // to Dubki
        {
            direction: "Слав.бульвар",
            time: "00:05",
            color: "#8DB929",
            hours: 0,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "01:00",
            color: "#202020",
            hours: 1,
            minutes: 0,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "01:40",
            color: "#202020",
            hours: 1,
            minutes: 40,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "06:45 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "07:20 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "08:05",
            color: "#006DFF",
            hours: 8,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "07:35 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "07:45 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "08:15 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "08:45 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "09:25 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "10:25 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "10:55 -> По приб.",
            color: "#202020",
            hours: "",
            minutes: "",
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "11:35",
            color: "#202020",
            hours: 11,
            minutes: 35,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "12:05",
            color: "#006DFF",
            hours: 12,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "12:15",
            color: "#202020",
            hours: 12,
            minutes: 15,
            whereTo: "toDubki",
        },
        {
            direction: "Слав.бульвар",
            time: "13:40",
            color: "#8DB929",
            hours: 13,
            minutes: 40,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "13:05",
            color: "#202020",
            hours: 13,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "13:45",
            color: "#202020",
            hours: 13,
            minutes: 45,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "14:20",
            color: "#202020",
            hours: 14,
            minutes: 20,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "14:30",
            color: "#006DFF",
            hours: 14,
            minutes: 30,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "15:05",
            color: "#202020",
            hours: 15,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "15:30",
            color: "#006DFF",
            hours: 15,
            minutes: 30,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "15:43",
            color: "#202020",
            hours: 15,
            minutes: 43,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "16:25",
            color: "#202020",
            hours: 16,
            minutes: 25,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "17:05",
            color: "#202020",
            hours: 17,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "17:10",
            color: "#006DFF",
            hours: 17,
            minutes: 10,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "17:22",
            color: "#202020",
            hours: 17,
            minutes: 22,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "17:22",
            color: "#202020",
            hours: 17,
            minutes: 55,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "18:15",
            color: "#202020",
            hours: 18,
            minutes: 15,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "18:37",
            color: "#202020",
            hours: 18,
            minutes: 37,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "18:45",
            color: "#006DFF",
            hours: 18,
            minutes: 45,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "19:10",
            color: "#006DFF",
            hours: 19,
            minutes: 10,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "19:10",
            color: "#202020",
            hours: 19,
            minutes: 10,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "19:30",
            color: "#006DFF",
            hours: 19,
            minutes: 30,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "19:45",
            color: "#202020",
            hours: 19,
            minutes: 45,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "20:05",
            color: "#202020",
            hours: 20,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "20:18",
            color: "#202020",
            hours: 20,
            minutes: 18,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "20:32",
            color: "#202020",
            hours: 20,
            minutes: 32,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "20:35",
            color: "#006DFF",
            hours: 20,
            minutes: 35,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "20:45",
            color: "#202020",
            hours: 20,
            minutes: 45,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "20:59",
            color: "#202020",
            hours: 20,
            minutes: 59,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "21:10",
            color: "#006DFF",
            hours: 21,
            minutes: 10,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "21:16",
            color: "#202020",
            hours: 21,
            minutes: 16,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "21:40",
            color: "#202020",
            hours: 21,
            minutes: 40,
            whereTo: "toDubki",
        },
        {
            direction: "Молодёжная",
            time: "22:05",
            color: "#006DFF",
            hours: 22,
            minutes: 5,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "22:15",
            color: "#202020",
            hours: 22,
            minutes: 15,
            whereTo: "toDubki",
        },
        {
            direction: "Слав.бульвар",
            time: "22:35",
            color: "#8DB929",
            hours: 22,
            minutes: 35,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "22:35",
            color: "#202020",
            hours: 22,
            minutes: 35,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "23:00",
            color: "#202020",
            hours: 23,
            minutes: 0,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "23:10",
            color: "#202020",
            hours: 23,
            minutes: 10,
            whereTo: "toDubki",
        },
        {
            direction: "Слав.бульвар",
            time: "23:35",
            color: "#8DB929",
            hours: 23,
            minutes: 35,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "23:35",
            color: "#202020",
            hours: 23,
            minutes: 35,
            whereTo: "toDubki",
        },
        {
            direction: "Одинцово",
            time: "23:55",
            color: "#202020",
            hours: 23,
            minutes: 55,
            whereTo: "toDubki",
        },
    ],
    saturday: [
        {
            direction: "Одинцово",
            time: "01:00",
            color: "#006DFF",
            hours: 1,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "06:40",
            color: "#006DFF",
            hours: 6,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "06:50",
            color: "#006DFF",
            hours: 6,
            minutes: 50,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "07:20",
            color: "#006DFF",
            hours: 7,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "07:25",
            color: "#006DFF",
            hours: 7,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "07:55",
            color: "#006DFF",
            hours: 7,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "07:55",
            color: "#006DFF",
            hours: 7,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "08:00",
            color: "#006DFF",
            hours: 8,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "08:05",
            color: "#006DFF",
            hours: 8,
            minutes: 5,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:30",
            color: "#006DFF",
            hours: 9,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:35",
            color: "#006DFF",
            hours: 9,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "09:40",
            color: "#006DFF",
            hours: 9,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "10:15",
            color: "#006DFF",
            hours: 10,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "10:35",
            color: "#006DFF",
            hours: 10,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Cлав.бульвар",
            time: "10:45",
            color: "#006DFF",
            hours: 10,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "10:50",
            color: "#006DFF",
            hours: 10,
            minutes: 50,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "11:15",
            color: "#006DFF",
            hours: 11,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "11:30",
            color: "#006DFF",
            hours: 11,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "11:45",
            color: "#006DFF",
            hours: 11,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "11:50",
            color: "#006DFF",
            hours: 11,
            minutes: 50,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "12:55",
            color: "#006DFF",
            hours: 12,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Cлав.бульвар",
            time: "12:30",
            color: "#006DFF",
            hours: 12,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Cлав.бульвар",
            time: "13:15",
            color: "#006DFF",
            hours: 13,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "13:25",
            color: "#006DFF",
            hours: 13,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "14:00",
            color: "#006DFF",
            hours: 14,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "14:25",
            color: "#006DFF",
            hours: 14,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "14:55",
            color: "#006DFF",
            hours: 14,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "15:03",
            color: "#006DFF",
            hours: 15,
            minutes: 3,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "16:05",
            color: "#006DFF",
            hours: 16,
            minutes: 5,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "16:35",
            color: "#006DFF",
            hours: 16,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "16:40",
            color: "#006DFF",
            hours: 16,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "17:25",
            color: "#006DFF",
            hours: 17,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "18:00",
            color: "#006DFF",
            hours: 18,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "18:20",
            color: "#006DFF",
            hours: 18,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "18:45",
            color: "#006DFF",
            hours: 18,
            minutes: 45,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "19:10",
            color: "#006DFF",
            hours: 19,
            minutes: 10,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "19:25",
            color: "#006DFF",
            hours: 19,
            minutes: 25,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "20:00",
            color: "#006DFF",
            hours: 20,
            minutes: 0,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "20:10",
            color: "#006DFF",
            hours: 20,
            minutes: 10,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "20:35",
            color: "#006DFF",
            hours: 20,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "20:35",
            color: "#006DFF",
            hours: 20,
            minutes: 35,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "20:50",
            color: "#006DFF",
            hours: 20,
            minutes: 50,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "21:15",
            color: "#006DFF",
            hours: 21,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Молодёжная",
            time: "21:30",
            color: "#006DFF",
            hours: 21,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Cлав.бульвар",
            time: "21:40",
            color: "#006DFF",
            hours: 21,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "21:50",
            color: "#006DFF",
            hours: 21,
            minutes: 50,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "22:10",
            color: "#006DFF",
            hours: 22,
            minutes: 10,
            whereTo: "toMoscow",
        },
        {
            direction: "Cлав.бульвар",
            time: "22:15",
            color: "#006DFF",
            hours: 22,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "22:40",
            color: "#006DFF",
            hours: 22,
            minutes: 40,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "22:55",
            color: "#006DFF",
            hours: 22,
            minutes: 55,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "23:15",
            color: "#006DFF",
            hours: 23,
            minutes: 15,
            whereTo: "toMoscow",
        },
        {
            direction: "Cлав.бульвар",
            time: "23:20",
            color: "#006DFF",
            hours: 23,
            minutes: 20,
            whereTo: "toMoscow",
        },
        {
            direction: "Одинцово",
            time: "23:40",
            color: "#006DFF",
            hours: 23,
            minutes: 40,
            whereTo: "toMoscow",
        },
    ],
    sunday: [
        {
            direction: "Cлав.бульвар",
            time: "06:30",
            color: "#006DFF",
            hours: 19,
            minutes: 30,
            whereTo: "toMoscow",
        },
        {
            direction: "Cлав.бульвар",
            time: "06:30",
            color: "#006DFF",
            hours: 21,
            minutes: 30,
            whereTo: "toDubki",
        },
    ],
};

// 14:30
